ShopApp/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.Models
{
    public class Category
    {
        public string CategoryName { get; set; }
    }
}

ShopApp/Models/ErrorViewModel.cs
using System;

namespace ShopApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShopApp/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.Models
{
    public class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string Category { get; set; }
    }
}

ShopApp/Models/RegisterModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.Models
{
    public class RegisterModel
    {
        [Display(Name ="First Name")]
        [Required]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        [Required]
        public string LastName { get; set; }
        [Display(Name = "Email")]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Display(Name = "Password")]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

ShopApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using ShopApp.Models;

namespace ShopApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Register()
        {
            return View();
        }
    }
}

ShopApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using ShopApp.Data;
using ShopApp.Models;

namespace ShopApp.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            using var con = new MySqlConnection(ApplicationDbContext.Value);
            var product = con.Query<Product>("select * from product", null, null, true, 0, CommandType.Text).ToList();
            return View(product);
        }
        public IActionResult Details(int id)
        {
            using var con = new MySqlConnection(ApplicationDbContext.Value);
            var param = new DynamicParameters();
            param.Add("@ID", id);
            var product = con.Query<Product>("select * from product where ID= @ID", param, null, true, 0, CommandType.Text).FirstOrDefault();
            return View(product);
        }
        public IActionResult CategoryIndex()
        {
            using var con = new MySqlConnection(ApplicationDbContext.Value);
            var categories = con.Query<Product>("select category from product group by category", null, null, true, 0, CommandType.Text).ToList();
            return View(categories);
        }
        public IActionResult ProductDetails(string categoryName)
        {
            using var con = new MySqlConnection(ApplicationDbContext.Value);
            var param = new DynamicParameters();
            param.Add("@Category", categoryName);
            var product = con.Query<Product>("select * from product where Category= @Category", param, null, true, 0, CommandType.Text).ToList();
            return View(product);
        }


    }
}

ShopApp/Controllers/ResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using ShopApp.Models;

namespace ShopApp.Controllers
{
    public class ResultController : Controller
    {
        [HttpGet]
        public IActionResult UserRegister(RegisterModel registerModel)
        {
            if (ModelState.IsValid)
            {
                ViewBag.FirstName = registerModel.FirstName;
                return View();
            }
            return View();
            
        }
    }
}

ShopApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 class="display-4">Welcome to GC Coffee Shop!</h3>
    <h1><a href="/Home/Register">Register</a></h1>
</div>

ShopApp/Views/Home/Register.cshtml
@model ShopApp.Models.RegisterModel

@{
    ViewData["Title"] = "Register";
}

<div class="alert alert-info">
    <strong>User Registration Form</strong>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Result" asp-action="UserRegister" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index" class="btn btn-primary">Back to Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ShopApp/Views/Product/CategoryIndex.cshtml
@model IEnumerable<ShopApp.Models.Product>

@{
    ViewData["Title"] = "CategoryIndex";
}

<div class="alert alert-success">
    <strong>Category List</strong>
</div>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    <a asp-action="ProductDetails" class="btn btn-info" asp-route-categoryName="@item.Category">Details</a>
                    @*@Html.ActionLink("Details", "Details", new {  categoryName=item.Category }) |*@

                </td>
            </tr>
        }
    </tbody>
</table>

ShopApp/Views/Product/Details.cshtml
@model ShopApp.Models.Product

@{
    ViewData["Title"] = "Details";
}

<div class="alert alert-success">
    <strong>Product Detail</strong>
</div>

<div>    
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
    </dl>
</div>
<div>   
    <a class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

ShopApp/Views/Product/Index.cshtml
@model IEnumerable<ShopApp.Models.Product>

@{
    ViewData["Title"] = "Index";
}
<div class="alert alert-success">
    <strong>Product List</strong>
</div>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>

                <td>
                    <a asp-action="Details" class="btn btn-info" asp-route-id="@item.ID">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ShopApp/Views/Product/ProductDetails.cshtml
@model IEnumerable<ShopApp.Models.Product>

@{
    ViewData["Title"] = "ProductDetails";
}

<div class="alert alert-success">
    <strong>Category Wise Product List</strong>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>

            </tr>
        }
    </tbody>
</table>
<div>
    <a class="btn btn-primary" asp-action="CategoryIndex">Back to List</a>
</div>

ShopApp/Views/Result/UserRegister.cshtml
@{
    ViewData["Title"] = "Register";
}

<div class="alert alert-success">
    <strong>Success!</strong> Welcome @ViewBag.FirstName for your registration
</div>

ShopApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShopApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="CategoryIndex">Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ShopApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>